### PR TITLE
fix(emitter): wrap listener in try catch

### PR DESCRIPTION
**Pull request by P0lip**

### CODE REVIEW

**Comment by wmhilton** [comment]
Bah that was supposed to be a Comment not a Request changes

**Comment by P0lip** [comment]
> Isn't it better to leave it unhandled so Sentry will report it?

No. We had an issue in Studio where 4-5 out of 9 listeners were not executed due to an exception that was thrown in one of the listeners.

Plus, the errors originated from that throwing listener were not reported for some reason :thinking:

**Comment by wmhilton** [comment]
> Plus, the errors originated from that throwing listener were not reported for some reason 🤔

Sounds to me like it's time to ditch our weird third-party event emitter and write our own 😆

**Comment by marbemac** [comment]
Generally exceptions thrown in async functions are silently swallowed unless handled right?

**Comment by P0lip** [comment]
> Sounds to me like it's time to ditch our weird third-party event emitter and write our own laughing

Yeah, I wrote 2 different event emitters in the past, so we could actually just toss one of them in, but I'm fine with keeping the existing one.
I kind of expected our emitter had issues with that, as IIRC one of my first PRs I reviewed at Stoplight was event emitter (located in some different repo initially) :laughing:. Most of implementations I examined, rightfully or not, do not account of exceptions and simply do not continue.

> Generally exceptions thrown in async functions are silently swallowed unless handled right?

No, there is an event you can subscribe to called `unhandledRejection`.
I think Sentry listens to it by default.

**Comment by marbemac** [comment]
> Yeah, I wrote 2 different event emitters in the past, so we could actually just toss one of them in, but I'm fine with keeping the existing one.

Yeah I agree re sticking with the current one.

**Pull request merged**
